---
title: "Lab 1"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Uzduotis NR 1
```{r}
#1.Realizuokite dvimačio Gauso atsitiktinių dydžių generavimo funkciją, kuri generuotų dydžius su vidurkiu M ir kovariacine matrica R (žr. variantų lentelę). Ši funkcija gali naudotis tik vienamačio standartinio Gauso atsitiktinio dydžio generatoriumi rnorm(n). Tolimesnei užduočiai naudokite šią savo sudarytą funkciją.

# 6 variantas - Vytautas Kraujalis
set.seed(6)

# Duoti vidurkiai
mu1 <- 9
mu2 <- 1

M <- c(mu1, mu2)

# Duota sigma matrica
R <- matrix(
   c(
      40, -10,
      -10, 4
   ),
   nrow = 2, ncol = 2
)

# -- 1 --

# Funkcija, kurios argumentai: N - imties dydis, M - Vidurkiu matrica, R - Kovariacine matrica. Funkcija grazina dvimati normaluji a.d. matricos pavidalus 2*N
DvimatisGausoAD <- function(N, M, R){
   # Cholesky dekompozicija
   
   # Transponuota cholesky dekompozicija
   Chol = t(chol(R))
   
   # Generuojam normaliuosius vienmacius a.d.
   Z = matrix(
      rnorm(2 * N),
      nrow = 2, ncol = N
   )
   DvimatisGauso = t(Chol %*% Z) +
      matrix(
         rep(M, N),
         byrow = T, ncol = 2
      )
   return(DvimatisGauso)
}

# -------
# -- 2 --

# Imties dydziu vektorius, su kuriais darysime bandymus
N <- c(10, 100, 1000, 10000)

print("Tikra kovariacine matrica:")
R

for(i in 1:length(N)){
   print(paste0("Kovariacine matrica, kai N = ", N[i]))
   print(round(cov(DvimatisGausoAD(N[i], M, R)), 1))
}

print("Tikri vidurkiai:")
M

for(i in 1:length(N)){
   print(paste0("Vidurkiai, kai N = ", N[i]))
   print(round(colMeans(DvimatisGausoAD(N[i], M, R)), 1))
}

# -------
# -- 3 --

library(ggplot2)
library(dplyr)

#Grafiko brezimas
BreztiSklaidosDiagrama <- function(DvimatisGausas){
   DvimatisGausas <- as.data.frame(DvimatisGausas)
   # Apskaiciuojam empirinius vidurkius, naudosime tasko padejimui sklaidos diagramoje
   EmpiriniaiVidurkiai <- DvimatisGausas %>% 
      summarise_all(mean)
   # Breziame a.d. sklaidos diagrame, elipsines kreives 95% ir 50% tiketinoms reiksmems ir empirinio vidurkio vieta
   ggplot(DvimatisGausas, aes(x = V1, y = V2)) +
      geom_point() +
      stat_ellipse(level = 0.5, color = "red", type = "norm", size = 1) +
      stat_ellipse(level = 0.95, color = "green", type = "norm", size = 1) +
      geom_point(data = EmpiriniaiVidurkiai, size = 4, color = "red", shape = 23, fill = "red") +
      theme_minimal()
}

# Kuomet keiciam imties dydi N
N <- c(10, 100, 1000, 2500, 5000, 10000)
DvimaciaiGauso <- list(
   DvimatisGausoAD(N[1], M, R),
   DvimatisGausoAD(N[2], M, R),
   DvimatisGausoAD(N[3], M, R),
   DvimatisGausoAD(N[4], M, R),
   DvimatisGausoAD(N[5], M, R),
   DvimatisGausoAD(N[6], M, R)
)
Labels <- list()
for(i in 1:length(N)){
   Labels[[i]] <- paste0("N = ", N[i])
}

cowplot::plot_grid(
   BreztiSklaidosDiagrama(DvimatisGausoAD(N[1], M, R)), 
   BreztiSklaidosDiagrama(DvimatisGausoAD(N[2], M, R)), 
   BreztiSklaidosDiagrama(DvimatisGausoAD(N[3], M, R)),
   BreztiSklaidosDiagrama(DvimatisGausoAD(N[4], M, R)),
   BreztiSklaidosDiagrama(DvimatisGausoAD(N[5], M, R)),
   BreztiSklaidosDiagrama(DvimatisGausoAD(N[6], M, R)),
   labels = Labels)
ggsave(paste0("Lab1_Grafikas_PagalN.png"), device = "png", width = 14, height = 7)

# Funkcija keisti parametrus ir brezti sklaidos diagrama
# PirmaKoord ir AntraKoord - koordinates, kuriu parametrus keisime; ReiksmeNuo - Koordinates reikmes, kuri bus pradiniu momentu; ReiksmesDidinimas - keliais vienetais didinsime koordinates reiksme; KiekReiksmiu - kiek susigeneruosime reiksmiu (grafikas nubres max 6); N - Imties dydis N
KeiciamParametrus <- function(PirmaKoord, AntraKoord, ReiksmeNuo, ReiksmesDidinimas, KiekReiksmiu, N){
   DvimaciaiGauso <- list()
   # Kovariacine matrica, kuri kiekvienos iteracijos metu igys nauja parametro reiksme
   KovariacineMatrica <- R
   # Isisaugosime koreliacijos koeficientus
   Koreliacijos <- NULL
   # Koordinates parametru reiksmes, kurias testuosime
   koordinate <- seq(ReiksmeNuo, by = ReiksmesDidinimas, length.out = KiekReiksmiu)
   for(i in 1:KiekReiksmiu){
      KovariacineMatrica[PirmaKoord, AntraKoord] <- koordinate[i]
      DvimaciaiGauso[[i]] <- DvimatisGausoAD(N, M, KovariacineMatrica)
      print(KovariacineMatrica)
      # Patikriname, ar tikrines reiksmes yra >= 0
      print(eigen(KovariacineMatrica)$values >= 0)
      # Apskaiciuojame ir issisaugome koreliacijos koeficienta
      Koreliacijos <- c(Koreliacijos, round(cov(DvimaciaiGauso[[i]][,1], DvimaciaiGauso[[i]][,2]) / ( sqrt(KovariacineMatrica[1,1]) * sqrt(KovariacineMatrica[2,2]) ), 3))
      print(Koreliacijos[i])
   
   }
   Labels <- list()
   for(i in 1:KiekReiksmiu){
      Labels[[i]] <- paste0("N = ", N, " Koord. ", PirmaKoord, ", ", AntraKoord, " reiksme = ", koordinate[i], ", kor. koef = ", Koreliacijos[i])
   }
   cowplot::plot_grid(
      BreztiSklaidosDiagrama(DvimaciaiGauso[[1]]), 
      BreztiSklaidosDiagrama(DvimaciaiGauso[[2]]), 
      BreztiSklaidosDiagrama(DvimaciaiGauso[[3]]),
      BreztiSklaidosDiagrama(DvimaciaiGauso[[4]]),
      BreztiSklaidosDiagrama(DvimaciaiGauso[[5]]),
      BreztiSklaidosDiagrama(DvimaciaiGauso[[6]]),
      labels = Labels,
      label_size = 12,
      label_x = -0.3)
   ggsave(paste0("Lab1_Grafikas_",paste(PirmaKoord,AntraKoord,ReiksmeNuo,ReiksmesDidinimas,KiekReiksmiu, sep = "_"), ".png"), device = "png", width = 14, height = 7)
}

# Kuomet didinam kovariacines matricos 1,1 koordinate
KeiciamParametrus(1, 1, 40, 10, 6, 1000)

# Kuomet mazinam kovariacines matricos 1,1 koordinate
KeiciamParametrus(1, 1, 40, -2, 6, 1000)

# Kuomet didinam kovariacines matricos 2,2 koordinate
KeiciamParametrus(2, 2, 10, 50, 6, 1000)

# Kuomet mazinam kovariacines matricos 2,2 koordinate
KeiciamParametrus(2, 2, 14, -2, 6, 1000)

# Kuomet didinam kovariacines matricos 1,2 koordinate
KeiciamParametrus(1, 2, -10, 4, 6, 1000)

# Kuomet mazinam kovariacines matricos 1,2 koordinate
KeiciamParametrus(1, 2, -7, -1, 6, 1000)

# Kuomet didinam kovariacines matricos 2,1 koordinate
KeiciamParametrus(2, 1, -10, 4, 6, 1000)

# Kuomet mazinam kovariacines matricos 2,1 koordinate
KeiciamParametrus(2, 1, -7, -1, 6, 1000)

# -------

# Literatura
# https://www.itl.nist.gov/div898/handbook/pmc/section5/pmc542.htm
# https://blog.revolutionanalytics.com/2016/08/simulating-form-the-bivariate-normal-distribution-in-r-1.html
# https://www2.stat.duke.edu/courses/Spring12/sta104.1/Lectures/Lec22.pdf

```
