---
title: "Daugiamatė Statistinė Analizė Lab 2, 6 variantas"
author: "Vytautas Kraujalis"
date: '2021-11-30'
output: 
  word_document:
    toc: true 
    toc_depth: 3
    number_sections: true
    highlight: tango
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Required packages
```{r}
library(dplyr)
library(factoextra)
library(caret)
```

# Uzd. 1
```{r}
set.seed(123)

data <- read.table("mnist.txt", sep = ",", header = T) %>% 
   filter(label %in% c(1, 3, 5, 7)) # 6 var.: 1357
```

# Uzd. 2
```{r}
spausdinti_grafika <- function(skaicius, kuri_irasa){
   image(t(matrix(data %>% filter(label == skaicius) %>% slice(kuri_irasa) %>% select(-label) %>% t() %>% as.vector(), 28, byrow = T))[1:28, 28:1])
}

# vienetai:
par(mfrow=c(2,2))
spausdinti_grafika(1, 1)
spausdinti_grafika(1, 2)
spausdinti_grafika(1, 3)
spausdinti_grafika(1, 4)

# trejetai:
par(mfrow=c(2,2))
spausdinti_grafika(3, 1)
spausdinti_grafika(3, 2)
spausdinti_grafika(3, 3)
spausdinti_grafika(3, 4)

# penketai:
par(mfrow=c(2,2))
spausdinti_grafika(5, 1)
spausdinti_grafika(5, 2)
spausdinti_grafika(5, 3)
spausdinti_grafika(5, 4)

# septynetai:
par(mfrow=c(2,2))
spausdinti_grafika(7, 1)
spausdinti_grafika(7, 2)
spausdinti_grafika(7, 3)
spausdinti_grafika(7, 4)
```

# Uzd. 3
```{r}
pca <- prcomp(data %>% select(-label), scale = FALSE)
fviz_eig(pca, ncp = 20, main = "Pagrindinių komponenčių (PC1 - PC20) dispersijos (%)", ylab = "Dispersija (%)", xlab = "Pagrindinė Komponentė")
```

# Uzd. 4
```{r}
pca_var <- pca$sdev^2
pca_var <- pca_var / sum(pca_var)

print(paste0("Pirmos 4 pagrindinės komponentės sumiškai savyje turi ", round(sum(pca_var[1:4]) * 100, digits = 2), "% dispersijos."))

dispersija <- 0
kiek_pca <- 0
while(dispersija < 0.9){
   kiek_pca <- kiek_pca + 1
   dispersija <- sum(pca_var[1:kiek_pca])
}

print(paste0("Tam, kad pasiektume 90% suminės dispersijos, mums reikia panaudoti pirmas ", kiek_pca, " pagrindines komponentes, su šiomis komponentinėmis, suminė dispersija sieka ", round(dispersija * 100, digits = 2), "%"))
```

# Uzd. 5
```{r}
skaitmenys <- as.factor(data$label)
fviz_pca_ind(pca,
             col.ind = skaitmenys, # color by groups
             legend.title = "Skaitmuo",
             label = "none",
             title = "PC1 ir PC2 sklaidos diagrama pagal skaitmenis"
             )
```

# Uzd. 6

```{r}
uzpildyti_pixeliai <- data %>% 
   sapply(function(x){sum(x > 0)}) %>% 
   sort(decreasing = TRUE)

uzpildyti_pixeliai <- uzpildyti_pixeliai[uzpildyti_pixeliai / nrow(data) > 0.1]
uzpildyti_pixeliai <- uzpildyti_pixeliai[-1]
```

Kadangi yra stulpelių (pixelių), kurie jokiose eilutėse nebūna užpildyti, atfiltruosim tik tuos stulpelius, kurių užpildyti (reikšmė > 0) bent 10% iš stebėjimų. Iš gautų stulpelių atrinksime atsitiktines 3 poras ir atvaizduosime grafiškai.

Atrenkam 6 atsitiktinius stulpelius:
```{r}
atsitiktines_poros <- sample(names(uzpildyti_pixeliai), 6, replace = F)
```

Atvaizduojame 3 atsitiktines poras:
```{r}
atsitiktiniai_data <- data %>% 
   select(all_of(atsitiktines_poros), label) %>% 
   mutate(label = as.factor(label))
atsitiktiniai_data_colnames <- colnames(atsitiktiniai_data)
colnames(atsitiktiniai_data) <- c("V1", "V2", "V3", "V4", "V5", "V6", "label")

atsitiktiniai_data %>% 
   ggplot(aes(x = V1, y = V2, color = label)) +
   geom_point() +
   xlab(atsitiktiniai_data_colnames[1]) +
   ylab(atsitiktiniai_data_colnames[2])

atsitiktiniai_data %>% 
   ggplot(aes(x = V3, y = V4, color = label)) +
   geom_point() +
   xlab(atsitiktiniai_data_colnames[3]) +
   ylab(atsitiktiniai_data_colnames[4])

atsitiktiniai_data %>% 
   ggplot(aes(x = V5, y = V6, color = label)) +
   geom_point() +
   xlab(atsitiktiniai_data_colnames[5]) +
   ylab(atsitiktiniai_data_colnames[6])
```

# Uzd. 7
```{r}
data <- data %>% 
   filter(label %in% c(1, 3)) %>% 
   mutate(label = as.factor(label))

pca <- prcomp(data %>% select(-label), scale = FALSE)

data_pcs <- pca$x %>% 
   bind_cols(label = data$label)

# 2 klasių tikslumo ištraukimui iš sumaišymo matricos
classAcc <- function(confusionMatrix) {
  class1 <- round(confusionMatrix$table[1, 1] / sum(confusionMatrix$table[, 1]) * 100, 1)
  class2 <- round(confusionMatrix$table[2, 2] / sum(confusionMatrix$table[, 2]) * 100, 1)
  bendras <- confusionMatrix$overall["Accuracy"] * 100
  acc <- c(class1, class2, bendras)
  names(acc) <- c(colnames(confusionMatrix$table), "Bendras")
  return(acc)
}

# Susidarom list'ą su 20 formulių
formules <- NULL
formules[[1]] <- "label ~ PC1"
for(i in 2:20){
   formules[[i]] <- "label ~ PC1"
   for(j in 2:i){
      formules[[i]] <- paste0(formules[[i]], " + PC", j)
   }
}

formules <- lapply(formules, as.formula)
```

```{r}
tikslumai <- NULL
for(i in 1:20){
   glm <- glm(formula = formules[[i]], data = data_pcs, family = "binomial")
   prob_pred = predict(glm, type = "response", newdata = data_pcs %>% select(-label))
   y_pred = ifelse(prob_pred > 0.5, 3, 1) %>% 
      as.factor()
   confusion_matrix <- confusionMatrix(y_pred, data_pcs$label)
   tikslumai[[i]] <- classAcc(confusion_matrix)
}


tikslumai_data <- do.call(rbind.data.frame, tikslumai) %>% 
   bind_cols(kiek_pca = 1:20)
colnames(tikslumai_data) <- c("skaitmuo_1", "skaitmuo_3", "bendras", "kiek_pca")


```

