---
title: "Daugiamatė Statistinė Analizė Lab 3, 6 variantas"
author: "Vytautas Kraujalis"
date: '2021-12-04'
output: 
  word_document:
    toc: true 
    toc_depth: 3
    number_sections: true
    highlight: tango
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Uzd. 1
## 1
```{r}
library(openxlsx)

atstumai <- read.xlsx("atstumai.xlsx", rowNames = TRUE)

knitr::kable(atstumai)
```

## 3
```{r}

dist_mat <- dist(atstumai, method = "euclidean")
hclust_average <- hclust(dist_mat, method = "average")
hclust_complete <- hclust(dist_mat, method = "complete")
hclust_centroid <- hclust(dist_mat, method = "centroid")
hclust_single <- hclust(dist_mat, method = "single")


png(file = "1uzd_3_average.png", width = 1200, height = 850)
plot(hclust_average, main = "Vidutinio atstumo metodas", cex = 2)
dev.off()

png(file = "1uzd_3_complete.png", width = 1200, height = 850)
plot(hclust_complete, main = "Tolimiausio kaimyno metodas", cex = 2)
dev.off()

png(file = "1uzd_3_centroid.png", width = 1200, height = 850)
plot(hclust_centroid, main = "Atstumo tarp centru metodas", cex = 2)
dev.off()

png(file = "1uzd_3_single.png", width = 1200, height = 850)
plot(hclust_single, main = "Artimiausio kaimyno metodas", cex = 2)
dev.off()
```



# Uzd. 2
## 1
```{r}
# Metric MDS
fit <- cmdscale(dist_mat)
fit
# plot solution
png(file = "2uzd_1_Metric.png", width = 1200, height = 850)
plot(fit, xlab="Koord. 1", ylab="Koord. 2", main="Metrinis daugiamačių skalių metodas", type="n" , cex = 2)
text(fit, labels = colnames(atstumai), cex=2)
dev.off()
```

```{r}
library(MASS)
# Sammon
fit <- sammon(dist_mat)
fit 
# plot solution
png(file = "2uzd_1_nonmetric.png", width = 1200, height = 850)
plot(fit$points, xlab="Koord. 1", ylab="Koord. 2", main="Ne metrinis daugiamačių skalių metodas", type="n", cex = 2)
text(fit$points, labels = colnames(atstumai), cex = 2) 
dev.off()
```


# Uzd. 3
## 1
```{r}
p1 <- p2 <- p3 <- 1/3

m1 <- c(0, 0, 0)
m2 <- c(-9, -5, 1)
m3 <- c(3.99618, 0, 6.930407)

R1 <- matrix(
  c(
    3.8571, 0, -0.2162,
    0, 8.344, 0,
    -0.2162, 0, 4.8989
  ),
  nrow = 3, ncol = 3
)
R2 <- matrix(
  c(
    3.83, 2.281, 0,
    2.281, 3.55, 0,
    0, 0, 7.573
  ),
  nrow = 3, ncol = 3
)
R3 <- matrix(
  c(
    9.935, 0, 0,
    0, 7.6078, -0.3615,
    0, -0.3615, 7.7082
  ),
  nrow = 3, ncol = 3
)
```

```{r}
library(mvtnorm)
library(mclust)

n1 <- sum(runif(100) < p1)
n2 <- sum(runif(100) < p1)
n3 <- 100 - n1 - n2

gauso_ad_100 <- rbind(rmvnorm(n1, m1, R1), rmvnorm(n2, m2, R2), rmvnorm(n3, m3, R3))

n1 <- sum(runif(500) < p1)
n2 <- sum(runif(500) < p1)
n3 <- 500 - n1 - n2

gauso_ad_500 <- rbind(rmvnorm(n1, m1, R1), rmvnorm(n2, m2, R2), rmvnorm(n3, m3, R3))

n1 <- sum(runif(3000) < p1)
n2 <- sum(runif(3000) < p1)
n3 <- 3000 - n1 - n2

gauso_ad_3000 <- rbind(rmvnorm(n1, m1, R1), rmvnorm(n2, m2, R2), rmvnorm(n3, m3, R3))
```



## 2
### N = 100
```{r}
# Klasterizavimas
fit <- Mclust(gauso_ad_100)

# Rezultatai
fit$BIC
fit$parameters
```

### N = 500
```{r}
# Klasterizavimas
fit <- Mclust(gauso_ad_500)

# Rezultatai
fit$BIC
fit$parameters
```

### N = 3000
```{r}
# Klasterizavimas
fit <- Mclust(gauso_ad_3000)

# Rezultatai
fit$BIC
fit$parameters
```


# Uzd. 4
## 1
```{r}
library(dplyr)
koordinates <- read.xlsx("koordinates.xlsx", rowNames = TRUE) %>% 
   mutate_all(as.numeric)

knitr::kable(koordinates)

koordinates <- scale(koordinates)

knitr::kable(koordinates)
```

## 2
### 2 klasteriai
```{r}
library(ggpubr)
library(tibble)
kmeans_2 <- kmeans(koordinates, centers = 2)
df <- koordinates %>% 
   as.data.frame() %>% 
   rownames_to_column("Miestas") %>% 
   bind_cols(klasteris = factor(kmeans_2$cluster))

ggscatter(
  df, x = "Pirma_Koord", y = "Antra_Koord", 
  color = "klasteris", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "klasteris", size = 1.5,  legend = "right", ggtheme = theme_minimal(),
  label = "Miestas", repel = TRUE, label.rectangle = TRUE, font.label = c(14)
) +
  stat_mean(aes(color = klasteris), size = 4)
ggsave(filename = "4uzd_2_2klasteriai.png", width = 14, height = 7, units = "in", bg = "white")
```

### 3 klasteriai
```{r}
kmeans_3 <- kmeans(koordinates, centers = 3)
df <- koordinates %>% 
   as.data.frame() %>% 
   rownames_to_column("Miestas") %>% 
   bind_cols(klasteris = factor(kmeans_3$cluster))

ggscatter(
  df, x = "Pirma_Koord", y = "Antra_Koord", 
  color = "klasteris", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "klasteris", size = 1.5,  legend = "right", ggtheme = theme_minimal(),
  label = "Miestas", repel = TRUE, label.rectangle = TRUE, font.label = c(14)
) +
  stat_mean(aes(color = klasteris), size = 4)
ggsave(filename = "4uzd_2_3klasteriai.png", width = 14, height = 7, units = "in", bg = "white")
```

### 4 klasteriai
```{r}
kmeans_4 <- kmeans(koordinates, centers = 4)
df <- koordinates %>% 
   as.data.frame() %>% 
   rownames_to_column("Miestas") %>% 
   bind_cols(klasteris = factor(kmeans_4$cluster))

ggscatter(
  df, x = "Pirma_Koord", y = "Antra_Koord", 
  color = "klasteris", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "klasteris", size = 1.5,  legend = "right", ggtheme = theme_minimal(),
  label = "Miestas", repel = TRUE, label.rectangle = TRUE, font.label = c(14)
) +
  stat_mean(aes(color = klasteris), size = 4)
ggsave(filename = "4uzd_2_4klasteriai.png", width = 14, height = 7, units = "in", bg = "white")
```

### 5 klasteriai
```{r}
kmeans_5 <- kmeans(koordinates, centers = 5)
df <- koordinates %>% 
   as.data.frame() %>% 
   rownames_to_column("Miestas") %>% 
   bind_cols(klasteris = factor(kmeans_5$cluster))

ggscatter(
  df, x = "Pirma_Koord", y = "Antra_Koord", 
  color = "klasteris", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "klasteris", size = 1.5,  legend = "right", ggtheme = theme_minimal(),
  label = "Miestas", repel = TRUE, label.rectangle = TRUE, font.label = c(14)
) +
  stat_mean(aes(color = klasteris), size = 4)
ggsave(filename = "4uzd_2_5klasteriai.png", width = 14, height = 7, units = "in", bg = "white")
```

## 3
```{r}
kmeans_2 <- kmeans(gauso_ad_500, centers = 2)
kmeans_3 <- kmeans(gauso_ad_500, centers = 3)
kmeans_4 <- kmeans(gauso_ad_500, centers = 4)
kmeans_5 <- kmeans(gauso_ad_500, centers = 5)
```

## 4
### 2 klasteriai
```{r}
df <- gauso_ad_500 %>% 
   as.data.frame() %>% 
   bind_cols(klasteris = factor(kmeans_2$cluster))

ggscatter(
  df, x = "V1", y = "V2", 
  color = "klasteris", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "klasteris", size = 1.5,  legend = "right", ggtheme = theme_minimal()
) +
  stat_mean(aes(color = klasteris), size = 4)
ggsave(filename = "4uzd_4_2klasteriai.png", width = 14, height = 7, units = "in", bg = "white")
```

### 3 klasteriai
```{r}
df <- gauso_ad_500 %>% 
   as.data.frame() %>% 
   bind_cols(klasteris = factor(kmeans_3$cluster))

ggscatter(
  df, x = "V1", y = "V2", 
  color = "klasteris", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "klasteris", size = 1.5,  legend = "right", ggtheme = theme_minimal()
) +
  stat_mean(aes(color = klasteris), size = 4)
ggsave(filename = "4uzd_4_3klasteriai.png", width = 14, height = 7, units = "in", bg = "white")
```

### 4 klasteriai
```{r}
df <- gauso_ad_500 %>% 
   as.data.frame() %>% 
   bind_cols(klasteris = factor(kmeans_4$cluster))

ggscatter(
  df, x = "V1", y = "V2", 
  color = "klasteris", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "klasteris", size = 1.5,  legend = "right", ggtheme = theme_minimal()
) +
  stat_mean(aes(color = klasteris), size = 4)
ggsave(filename = "4uzd_4_4klasteriai.png", width = 14, height = 7, units = "in", bg = "white")
```

### 5 klasteriai
```{r}
df <- gauso_ad_500 %>% 
   as.data.frame() %>% 
   bind_cols(klasteris = factor(kmeans_5$cluster))

ggscatter(
  df, x = "V1", y = "V2", 
  color = "klasteris", palette = "npg", ellipse = TRUE, ellipse.type = "convex",
  shape = "klasteris", size = 1.5,  legend = "right", ggtheme = theme_minimal()
) +
  stat_mean(aes(color = klasteris), size = 4)
ggsave(filename = "4uzd_4_5klasteriai.png", width = 14, height = 7, units = "in", bg = "white")
```

## 5
```{r}
kvad_sumos <- NULL
klasteriai <- 1:10

for(i in 1:length(klasteriai)){
   kvad_sumos[i] <- kmeans(gauso_ad_500, centers = i)$tot.withinss
}

png(file = "4uzd_5.png", width = 1200, height = 850)
plot(klasteriai, kvad_sumos, type = "l", cex = 2)
dev.off()
```

## 6
```{r}
library(factoextra)

png(file = "6uzd.png", width = 1200, height = 850)
fviz_nbclust(gauso_ad_500, kmeans, method = "silhouette")
dev.off()
```

